name: Build and run tests
on:
  push: {}
  pull_request: {}
jobs:
  run:
    runs-on: macOS-latest
    name: Build and run tests
    steps:
    - uses: actions/checkout@master
    - name: Xcode version
      run: /usr/bin/xcode-select --print-path
    - name: Install LLVM
      run: |
        export PATH=/usr/local/opt/llvm/bin:"${PATH}"
        brew update
        brew install llvm@8
        swift package resolve
        sudo swift .build/checkouts/LLVMSwift/utils/make-pkgconfig.swift
    - name: Build
      run: swift build
    - name: Test
      run: swift test
